---
title: "F1 2022: Some Mid-Season Driver Statistics"
author: "Marco Hui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,fig.width=12, fig.height=8)
```

```{r Packages}
# load packages
library(readr)
library(tidyverse)
```

```{r Colour Hex Codes}
# store constructor colour hex codes in variables
alfa_clr='#900000'
alpha_clr='#2B4562'
alpine_clr='#0090FF'
aston_clr='#006F62'
ferrari_clr='#DC0000'
haas_clr='#FFFFFF'
mclaren_clr='#FF8700'
mercedes_clr='#00D2BE'
redbull_clr='#0600EF'
williams_clr='#005AFF'
```

```{r Plot Theme}
# create plot theme
hui_ggplot <- theme(plot.title = element_text(face='bold',size=22,vjust=1),
                   axis.title.x = element_blank(),
                   axis.title.y = element_blank(),
                   text = element_text(color='white'),
                   axis.text = element_text(color='white',size=15),
                   legend.position='right',
                   legend.background = element_rect(fill='#1e2226',colour='#1e2226'),
                   legend.key = element_rect(fill='#1e2226',colour='#1e2226'),
                   plot.background = element_rect(fill='#1e2226',colour='#1e2226'),
                   panel.background = element_rect(fill='#1e2226',colour='#1e2226'),
                   panel.grid.major = element_line(colour="grey27"),
                   panel.grid.major.x = element_blank(),
                   panel.grid.minor = element_blank(),
                   panel.border = element_blank())
```

```{r Data}
# load data sets from csv files
race_results <- read_csv('/Users/marcohui/Desktop/2022driverstats/results2022.csv')
starting_grid <- read_csv('/Users/marcohui/Desktop/2022driverstats/starts2022.csv')
fastest_laps <- read_csv('/Users/marcohui/Desktop/2022driverstats/flaps2022.csv')
sprint_results <- read_csv('/Users/marcohui/Desktop/2022driverstats/sprints2022.csv')
quali_results <- read_csv('/Users/marcohui/Desktop/2022driverstats/qualis2022.csv')

# change driver names to acronym

race_results <- race_results %>% mutate(Driver=str_sub(Driver,-3,-1))
starting_grid <- starting_grid %>% mutate(Driver=str_sub(Driver,-3,-1))
fastest_laps <- fastest_laps %>% mutate(Driver=str_sub(Driver,-3,-1))
sprint_results <- sprint_results %>% mutate(Driver=str_sub(Driver,-3,-1))
quali_results <- quali_results %>% mutate(Driver=str_sub(Driver,-3,-1))
```

```{r, include=FALSE}
# make sure columns are identical
colnames(race_results)
colnames(sprint_results)

# combine two dataframes
all_results <- rbind(race_results,sprint_results)
all_results
```

## Number of Points
```{r}
driverPoints <- all_results %>% 
  group_by(Driver,Car) %>%
  summarise(driverPoints=sum(PTS)) %>%
  arrange(-driverPoints)

driverPoints %>% ggplot() + 
  geom_bar(aes(x=reorder(Driver,-driverPoints),y=driverPoints,fill=Car),
           stat='identity',show.legend=FALSE) +
  labs(title='Number of Championship Points by Driver') +
  scale_y_continuous(breaks=c(0,25,50,75,100,125,150,175,200,225,250),expand=c(0,0)) +
  scale_fill_manual(values=c(alfa_clr,alpha_clr,alpine_clr,aston_clr,ferrari_clr,
                             haas_clr,mclaren_clr,mercedes_clr,redbull_clr,williams_clr)) +
  hui_ggplot
```

## Percentage of Team Points
```{r}
teamPoints <- all_results %>% group_by(Car) %>%
  summarise(teamPoints=sum(PTS)) %>%
  arrange(-teamPoints)

sharePoints <- driverPoints %>% 
  left_join(teamPoints,by='Car') %>%
  mutate(sharePoints=driverPoints/teamPoints)

sharePoints %>% ggplot() + 
  geom_bar(aes(x=reorder(Driver,-sharePoints),y=sharePoints,fill=Car),
           stat='identity',show.legend=FALSE) +
  labs(title='Percetange of Team Championship Points by Driver') +
  scale_fill_manual(values=c(alfa_clr,alpha_clr,alpine_clr,aston_clr,ferrari_clr,
                             haas_clr,mclaren_clr,mercedes_clr,redbull_clr,williams_clr)) +
  hui_ggplot
```

## Number of Race Laps Completed
```{r}
laps <- race_results %>%
  group_by(Driver,Car) %>%
  summarise(lapsCompleted=sum(Laps)) %>%
  arrange(-lapsCompleted)

laps %>% ggplot() + 
  geom_bar(aes(x=reorder(Driver,-lapsCompleted),y=lapsCompleted,fill=Car),
           stat='identity',show.legend=FALSE) +
  labs(title='Number of Race Laps Completed by Driver (Sprints Excluded)') +
  scale_fill_manual(values=c(alfa_clr,alpha_clr,alpine_clr,aston_clr,ferrari_clr,
                             haas_clr,mclaren_clr,mercedes_clr,redbull_clr,williams_clr)) +
  hui_ggplot
```

## Number of DNFs
```{r}
dnfs <- race_results %>%
  mutate(dnf=`Time/Retired`=='DNF') %>%
  group_by(Driver,Car) %>%
  summarise(dnfs=sum(dnf)) %>%
  arrange(-dnfs)

dnfs %>% ggplot() + 
  geom_bar(aes(x=reorder(Driver,-dnfs),y=dnfs,fill=Car),
           stat='identity',show.legend=FALSE) +
  labs(title='Number of DNFs by Driver (Sprints Excluded)') +
  scale_fill_manual(values=c(alfa_clr,alpha_clr,alpine_clr,aston_clr,ferrari_clr,
                             haas_clr,mclaren_clr,mercedes_clr,redbull_clr,williams_clr)) +
  hui_ggplot
```

## Average Race Finishing Position
```{r}
avgfinpos <- race_results %>% 
  filter(`Time/Retired`!='DNF'&`Time/Retired`!='DNS') %>%
  mutate(Pos=as.numeric(Pos)) %>%
  group_by(Driver,Car) %>%
  summarise(avgFinPos=round(mean(Pos),2)) %>%
  arrange(avgFinPos)

avgfinpos %>% ggplot(aes(x=reorder(Driver,avgFinPos),y=avgFinPos,fill=Car)) + 
  geom_bar(stat='identity',show.legend=FALSE) +
  geom_text(aes(label=avgFinPos),vjust=-0.2,colour='white',size=5) +
  labs(title='Average Race Finishing Position by Driver (excludes Sprints)') +
  scale_fill_manual(values=c(alfa_clr,alpha_clr,alpine_clr,aston_clr,ferrari_clr,
                             haas_clr,mclaren_clr,mercedes_clr,redbull_clr,williams_clr)) +
  hui_ggplot
```

## Median Race Finishing Position
```{r}
medfinpos <- race_results %>% 
  filter(`Time/Retired`!='DNF'&`Time/Retired`!='DNS') %>%
  mutate(Pos=as.numeric(Pos)) %>%
  group_by(Driver,Car) %>%
  summarise(medFinPos=round(median(Pos),2)) %>%
  arrange(medFinPos)

medfinpos %>% ggplot(aes(x=reorder(Driver,medFinPos),y=medFinPos,fill=Car)) + 
  geom_bar(stat='identity',show.legend=FALSE) +
  geom_text(aes(label=medFinPos),vjust=-0.2,colour='white',size=5) +
  labs(title='Median Race Finishing Position by Driver (Sprints Excluded)') +
  scale_fill_manual(values=c(alfa_clr,alpha_clr,alpine_clr,aston_clr,ferrari_clr,
                             haas_clr,mclaren_clr,mercedes_clr,redbull_clr,williams_clr)) +
  hui_ggplot
```

## Driver Salary Cost per Point
```{r Salary Table}
# create tibble for driver base salaries (in millions USD)
salary <- tribble(
  ~No,~Salary,
  44,40000000, 
  1,25000000,
  14,20000000,
  4,20000000,
  5,15000000,
  3,15000000,
  16,12000000,
  77,10000000,
  18,10000000,
  55,10000000,
  11,8000000,
  20,6000000,
  10,5000000,
  31,5000000,
  63,5000000,
  23,2000000,
  47,1000000,
  24,1000000,
  6,1000000,
  22,750000
)
```

```{r}
salarypoints <- all_results %>% 
  filter(No!=27) %>%
  group_by(No,Driver,Car,) %>%
  summarise(driverPoints=sum(PTS)) %>%
  left_join(salary,by='No') %>%
  mutate(dollarperpoint=Salary/driverPoints) %>%
  mutate(dollarperpoint_k=round((dollarperpoint/1000),2)) %>%
  arrange(dollarperpoint_k)

salarypoints %>% ggplot(aes(x=reorder(Driver,dollarperpoint_k),y=dollarperpoint_k,fill=Car)) + 
  geom_bar(stat='identity',show.legend=FALSE) +
  geom_text(aes(label=dollarperpoint_k),vjust=-0.2,colour='white',size=4) +
  labs(title='Salary Cost Per Point by Driver (in Thousands)') +
  scale_fill_manual(values=c(alfa_clr,alpha_clr,alpine_clr,aston_clr,ferrari_clr,
                             haas_clr,mclaren_clr,mercedes_clr,redbull_clr,williams_clr)) +
  hui_ggplot

```

